[package]
name = "zhazba_render_derive"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
# Internal crates
zhazba_lua = { workspace = true }

# External packages
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
