[package]
name = "zhazba_lua"
version = "0.1.0"
edition = "2024"

[dependencies]
# Internal crate
zhazba_lua_derive = { path = "../zhazba_lua_derive" }

# External packages
anyhow = { workspace = true }
mlua = { workspace = true }
once_cell = { workspace = true }
tracing = { workspace = true }
