[package]
name = "zhazba_config"
version = "0.1.0"
edition = "2024"

[dependencies]
# Internal crates
zhazba_action = { workspace = true }
zhazba_lua = { workspace = true }

# External packages
parking_lot = { workspace = true }
