[package]
name = "zhazba_logger"
version = "0.1.0"
edition = "2024"

[dependencies]
# External packages
tracing = { workspace = true }
tracing-appender = { workspace = true }
tracing-error = { workspace = true }
tracing-subscriber = { workspace = true }
